---
- name: Backup Huawei Firewall (AWX collected artifacts)
  hosts: bj
  gather_facts: false

  vars:
    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"
    keep_days: 30

  tasks:
    - name: Show isolated dir
      debug:
        msg:
          - "AWX_ISOLATED_DATA_DIR={{ lookup('env','AWX_ISOLATED_DATA_DIR') | default('NOT_SET', true) }}"
          - "RUNNER_ARTIFACTS_DIR={{ lookup('env','RUNNER_ARTIFACTS_DIR') | default('NOT_SET', true) }}"

    - name: Set artifacts paths (must be under AWX_ISOLATED_DATA_DIR/artifacts)
      set_fact:
        isolated_dir: "{{ lookup('env','AWX_ISOLATED_DATA_DIR') | default('/runner', true) }}"
        artifacts_base: "{{ (lookup('env','AWX_ISOLATED_DATA_DIR') | default('/runner', true)) }}/artifacts"
        out_root: "{{ (lookup('env','AWX_ISOLATED_DATA_DIR') | default('/runner', true)) }}/artifacts/backups"
        out_dir: "{{ (lookup('env','AWX_ISOLATED_DATA_DIR') | default('/runner', true)) }}/artifacts/backups/{{ inventory_hostname }}/{{ today }}"
        out_file: "{{ (lookup('env','AWX_ISOLATED_DATA_DIR') | default('/runner', true)) }}/artifacts/backups/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"

    - name: Create artifacts output directory
      file:
        path: "{{ out_dir }}"
        state: directory
        mode: "0755"

    - name: Disable terminal paging (best effort)
      ansible.netcommon.cli_command:
        command: screen-length 0 temporary
      ignore_errors: true

    - name: Get firewall configuration
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    - name: Save configuration to AWX artifacts (will be collected)
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ out_file }}"
        mode: "0644"

    - name: Confirm file exists
      command: bash -lc "ls -lah '{{ out_file }}' | cat"
      changed_when: false

    - name: Cleanup old backups inside artifacts (best effort)
      shell: |
        find "{{ out_root }}/{{ inventory_hostname }}" -type f -name "*.cfg" -mtime +{{ keep_days }} -delete
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: false
