---
- name: Backup Huawei Firewall to AWX Artifacts
  hosts: bj
  gather_facts: false

  vars:
    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"
    out_dir: "{{ awx_job_dir }}/artifacts/backups/{{ inventory_hostname }}/{{ today }}"
    out_file: "{{ out_dir }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"

  tasks:
    - name: Show awx_job_dir
      debug:
        msg:
          - "awx_job_dir={{ awx_job_dir | default('NOT_SET') }}"
          - "out_file={{ out_file }}"

    - name: Create artifacts dir
      file:
        path: "{{ out_dir }}"
        state: directory
        mode: "0755"

    - name: Get firewall configuration
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    - name: Save configuration to artifacts
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ out_file }}"
        mode: "0644"
