---
- name: Backup Huawei Firewall (save locally then fetch to controller)
  hosts: bj
  gather_facts: false

  vars:
    # runner 本地临时目录（一定可写）
    tmp_root: "/tmp/backups"

    # 目标：projects PVC 下你的项目目录（目前是 _9__bj）
    pvc_root: "/var/lib/awx/projects/_9__bj/backups"

    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"
    keep_days: 30

  tasks:
    - name: Get firewall configuration (on device)
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    # ===== 在 runner 本地生成文件（不是在设备上）=====
    - name: Create temp dir on runner (localhost)
      command: mkdir -p "{{ tmp_root }}/{{ inventory_hostname }}/{{ today }}"
      delegate_to: localhost
      changed_when: false

    - name: Save cfg to runner temp file (localhost)
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ tmp_root }}/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        mode: "0644"
      delegate_to: localhost

    - name: List temp file (localhost)
      command: bash -lc "ls -la {{ tmp_root }}/{{ inventory_hostname }}/{{ today }} | tail -n 20"
      delegate_to: localhost
      changed_when: false

    # ===== 确保 controller 侧目录存在（尽量做，不行也不阻塞）=====
    - name: Ensure dest dir exists on projects PVC (controller side best effort)
      command: mkdir -p "{{ pvc_root }}/{{ inventory_hostname }}/{{ today }}"
      delegate_to: localhost
      changed_when: false
      failed_when: false

    # ===== 从 runner 拉回到 controller 并写入 pvc_root =====
    - name: Fetch cfg from runner to controller into projects PVC
      fetch:
        src: "{{ tmp_root }}/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        dest: "{{ pvc_root }}/{{ inventory_hostname }}/{{ today }}/"
        flat: true
      delegate_to: localhost

    - name: Cleanup old backups on projects PVC (best effort)
      shell: |
        find "{{ pvc_root }}/{{ inventory_hostname }}" -type f -name "*.cfg" -mtime +{{ keep_days }} -delete
      args:
        executable: /bin/bash
      delegate_to: localhost
      changed_when: false
      failed_when: false
