---
- name: Backup Huawei Firewall to AWX Projects PV
  hosts: bj
  gather_facts: false

  vars:
    backup_root: "/var/lib/awx/projects/backups"
    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"
    keep_days: 30

  tasks:
    - name: Ensure backups base dir exists (under projects PV)
      file:
        path: "{{ backup_root }}"
        state: directory
        mode: "0775"

    - name: Disable terminal paging (best effort)
      ansible.netcommon.cli_command:
        command: screen-length 0 temporary
      ignore_errors: true

    - name: Ensure device/date directory exists
      file:
        path: "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}"
        state: directory
        mode: "0775"

    - name: Get firewall configuration
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    - name: Save configuration to file
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        mode: "0664"

    - name: Find old backup files
      find:
        paths: "{{ backup_root }}/{{ inventory_hostname }}"
        recurse: true
        file_type: file
        age: "{{ keep_days }}d"
      register: old_files

    - name: Remove old backup files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_files.files }}"
      when: old_files.matched | int > 0
