---
- name: Backup Huawei Firewall and push to Git
  hosts: bj
  gather_facts: false

  vars:
    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"
    keep_days: 30

    repo_root: "{{ playbook_dir }}"                 # AWX checkout 目录，通常 /runner/project
    backup_root: "{{ playbook_dir }}/backups"       # 写入仓库内 backups/
    git_user_name: "awx-backup-bot"
    git_user_email: "awx-backup-bot@example.local"

  tasks:
    - name: Show repo root
      debug:
        msg:
          - "repo_root={{ repo_root }}"
          - "backup_root={{ backup_root }}"

    - name: Ensure backup dir exists
      file:
        path: "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}"
        state: directory
        mode: "0755"

    - name: Disable terminal paging (best effort)
      ansible.netcommon.cli_command:
        command: screen-length 0 temporary
      ignore_errors: true

    - name: Get firewall configuration
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    - name: Write cfg into repo
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        mode: "0644"

    - name: Cleanup old backups (best effort)
      shell: |
        find "{{ backup_root }}/{{ inventory_hostname }}" -type f -name "*.cfg" -mtime +{{ keep_days }} -delete
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: false

    # --- Git commit/push ---
    - name: Configure git identity (local repo)
      shell: |
        git config user.name "{{ git_user_name }}"
        git config user.email "{{ git_user_email }}"
      args:
        chdir: "{{ repo_root }}"
        executable: /bin/bash
      changed_when: false

    - name: Show git status
      shell: git status --porcelain
      args:
        chdir: "{{ repo_root }}"
        executable: /bin/bash
      register: git_status
      changed_when: false

    - name: Commit and push if changes
      shell: |
        set -e
        git add backups/
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit."
          exit 0
        fi
        git commit -m "backup({{ inventory_hostname }}): {{ today }} {{ timestamp }}"
        # 尝试直接 push；失败则 rebase 后再 push（处理并发）
        git push || (git pull --rebase && git push)
      args:
        chdir: "{{ repo_root }}"
        executable: /bin/bash
      when: git_status.stdout | length > 0
