- hosts: bj
  gather_facts: false
  tasks:
    - name: backup running config
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    - name: save to project dir
      copy:
        content: "{{ cfg.stdout[0] }}"
        dest: "/runner/project/backups/{{ inventory_hostname }}_{{ lookup('pipe','date +%F_%H%M%S') }}.cfg"
