---
- name: Backup Huawei Firewall and push to Git
  hosts: bj
  gather_facts: false

  vars:
    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"
    keep_days: 30

    repo_root: "{{ playbook_dir }}"                 # AWX checkout 目录，通常 /runner/project
    backup_root: "{{ playbook_dir }}/backups"       # 写入仓库内 backups/
    git_user_name: "awx-backup-bot"
    git_user_email: "awx-backup-bot@example.local"

  tasks:
    - name: Show repo root
      debug:
        msg:
          - "repo_root={{ repo_root }}"
          - "backup_root={{ backup_root }}"

    - name: Ensure backup dir exists
      file:
        path: "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}"
        state: directory
        mode: "0755"

    - name: Disable terminal paging (best effort)
      ansible.netcommon.cli_command:
        command: screen-length 0 temporary
      ignore_errors: true

    - name: Get firewall configuration
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    - name: Write cfg into repo
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        mode: "0644"

    - name: Cleanup old backups (best effort)
      shell: |
        find "{{ backup_root }}/{{ inventory_hostname }}" -type f -name "*.cfg" -mtime +{{ keep_days }} -delete
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: false

    # --- Git commit/push ---
    - name: Debug playbook_dir and list
      shell: |
        echo "playbook_dir={{ playbook_dir }}"
        pwd
        ls -la "{{ playbook_dir }}" | head -n 200 || true
        find "{{ playbook_dir }}" -maxdepth 3 -type d -name ".git" -print || true
      args:
        executable: /bin/bash
      changed_when: false

    - name: Discover git repo root (nearest .git)
      shell: |
        set -e
        d="{{ playbook_dir }}"
        # 向上找 5 层（够用）
        for i in 0 1 2 3 4 5; do
          if [ -d "$d/.git" ]; then
            echo "$d"
            exit 0
          fi
          d="$(dirname "$d")"
        done
        # 向下找 3 层（有时 playbook 在子目录）
        f="$(find "{{ playbook_dir }}" -maxdepth 3 -type d -name .git | head -n 1 || true)"
        if [ -n "$f" ]; then
          dirname "$f"
          exit 0
        fi
        echo "NO_GIT_REPO_FOUND"
        exit 0
      args:
        executable: /bin/bash
      register: repo_root_detect
      changed_when: false

    - name: Fail if not a git repo (show hint)
      fail:
        msg: >
          Cannot find a git repo (.git) around playbook_dir={{ playbook_dir }}.
          Ensure AWX Project is SCM-based and synced successfully.
      when: repo_root_detect.stdout == "NO_GIT_REPO_FOUND"

    - name: Set repo_root fact
      set_fact:
        repo_root: "{{ repo_root_detect.stdout }}"

    - name: Configure git identity (local repo)
      shell: |
        git config user.name "awx-backup-bot"
        git config user.email "awx-backup-bot@example.local"
      args:
        chdir: "{{ repo_root }}"
        executable: /bin/bash
      changed_when: false
