---
- name: Backup Huawei Firewall (fetch to projects PVC)
  hosts: bj
  gather_facts: false

  vars:
    # runner 容器里临时保存一份（job 运行时肯定可写）
    tmp_root: "/tmp/backups"

    # ✅ 目标：写入 projects PVC（当前已确认项目目录为 _9__bj）
    # 如果以后目录名变了，我可以再给你做“自动发现项目目录”的版本
    pvc_root: "/var/lib/awx/projects/_9__bj/backups"

    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"
    keep_days: 30

  tasks:
    - name: Show paths (debug)
      debug:
        msg:
          - "tmp_root={{ tmp_root }}"
          - "pvc_root={{ pvc_root }}"
          - "today={{ today }}"
          - "timestamp={{ timestamp }}"

    - name: Create temp dir on runner
      command: mkdir -p "{{ tmp_root }}/{{ inventory_hostname }}/{{ today }}"
      changed_when: false

    - name: Disable terminal paging (best effort)
      ansible.netcommon.cli_command:
        command: screen-length 0 temporary
      ignore_errors: true

    - name: Get firewall configuration
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    - name: Save cfg on runner tmp
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ tmp_root }}/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        mode: "0644"

    # 目标目录在 controller(=AWX 侧)创建；即使 mkdir 失败也继续尝试 fetch
    - name: Ensure dest dir exists on projects PVC (controller side)
      command: mkdir -p "{{ pvc_root }}/{{ inventory_hostname }}/{{ today }}"
      changed_when: false
      failed_when: false

    # 关键：fetch 会把 src(远端/runner) 拉回 controller(AWX) 并写到 pvc_root
    - name: Fetch cfg back to controller into projects PVC
      fetch:
        src: "{{ tmp_root }}/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        dest: "{{ pvc_root }}/{{ inventory_hostname }}/{{ today }}/"
        flat: true

    - name: Cleanup old backups on projects PVC (best effort)
      shell: |
        find "{{ pvc_root }}/{{ inventory_hostname }}" -type f -name "*.cfg" -mtime +{{ keep_days }} -delete
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: false

    - name: List last 5 backups on projects PVC (controller side)
      shell: |
        ls -lt "{{ pvc_root }}/{{ inventory_hostname }}/{{ today }}" | head -n 6
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: false
