---
- name: Backup Huawei Firewall (AWX Artifacts)
  hosts: bj
  gather_facts: false

  vars:
    backup_root: "/runner/artifacts/backups"
    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"
    keep_days: 30

  tasks:
    - name: Debug paths
      command: bash -lc "id; umask; ls -ld /runner /runner/artifacts || true; mount | head -n 50"
      changed_when: false

    - name: Create backup directory
      command: mkdir -p "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}"
      changed_when: false

    - name: Disable terminal paging (best effort)
      ansible.netcommon.cli_command:
        command: screen-length 0 temporary
      ignore_errors: true

    - name: Get firewall configuration
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    - name: Save configuration to file
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        mode: "0644"

    - name: Cleanup old backups (best effort)
      shell: |
        find "{{ backup_root }}/{{ inventory_hostname }}" -type f -name "*.cfg" -mtime +{{ keep_days }} -delete
      args:
        executable: /bin/bash
      changed_when: false
      failed_when: false
