---
- name: Backup Huawei Firewall to Projects PVC via task container
  hosts: bj
  gather_facts: false

  vars:
    backup_root: "/var/lib/awx/projects/backups"
    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"
    keep_days: 30

  tasks:
    - name: Disable terminal paging (best effort)
      ansible.netcommon.cli_command:
        command: screen-length 0 temporary
      ignore_errors: true

    - name: Get firewall configuration (run on network device)
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    # ===== 写入 PVC：委派给 localhost（task 容器）=====
    - name: Create backup directory on projects PVC (task container)
      command: mkdir -p "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}"
      delegate_to: localhost
      changed_when: false

    - name: Save configuration to file on projects PVC (task container)
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/{{ today }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
        mode: "0644"
      delegate_to: localhost

    - name: Cleanup old backups on projects PVC (task container)
      shell: |
        find "{{ backup_root }}/{{ inventory_hostname }}" -type f -name "*.cfg" -mtime +{{ keep_days }} -delete
      args:
        executable: /bin/bash
      delegate_to: localhost
      changed_when: false
      failed_when: false
