- hosts: bj
  gather_facts: false
  tasks:
    - name: display version
      community.network.ce_command:
        commands:
          - display version
      register: out

    - debug:
        var: out.stdout_lines
