---
- name: Backup Huawei Firewall to Projects PVC via kubectl exec
  hosts: bj
  gather_facts: false

  vars:
    ns: "awx"
    task_deploy: "awx-demo-task"

    pvc_root: "/var/lib/awx/projects/_9__bj/backups"

    today: "{{ lookup('pipe', 'date +%F') }}"
    timestamp: "{{ lookup('pipe', 'date +%F_%H%M%S') }}"

    tmp_file: "/tmp/{{ inventory_hostname }}_{{ timestamp }}.cfg"
    dest_dir: "{{ pvc_root }}/{{ inventory_hostname }}/{{ today }}"
    dest_file: "{{ dest_dir }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"

  tasks:
    - name: Get firewall configuration
      community.network.ce_command:
        commands:
          - display current-configuration
      register: cfg

    - name: Write cfg to runner tmp file
      copy:
        content: "{{ cfg.stdout[0] | string }}"
        dest: "{{ tmp_file }}"
        mode: "0644"

    - name: Ensure dest dir on task pod (projects PVC)
      command: >
        kubectl -n {{ ns }} exec deploy/{{ task_deploy }} -- bash -lc
        "mkdir -p '{{ dest_dir }}' && ls -ld '{{ pvc_root }}' '{{ dest_dir }}'"
      changed_when: false

    - name: Copy tmp file content into task pod dest file (projects PVC)
      shell: |
        set -e
        # 把本地 tmp_file 内容通过 stdin 写到 task pod 的 dest_file
        kubectl -n {{ ns }} exec -i deploy/{{ task_deploy }} -- bash -lc "cat > '{{ dest_file }}' && chmod 0644 '{{ dest_file }}'"
      args:
        executable: /bin/bash
      changed_when: true
      # 关键：把文件内容喂给上面的命令
      stdin: "{{ lookup('file', tmp_file) }}"

    - name: Verify file exists on task pod
      command: >
        kubectl -n {{ ns }} exec deploy/{{ task_deploy }} -- bash -lc
        "ls -la '{{ dest_file }}' && tail -n 3 '{{ dest_file }}' | sed -e 's/./*/g' || true"
      changed_when: false
